# Generated by Django 5.0.6 on 2024-06-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('admission_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=12)),
                ('attendance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('attendance', models.PositiveIntegerField()),
                ('contact_no', models.CharField(max_length=12)),
                ('address', models.TextField()),
            ],
        ),
    ]
